import axios from 'axios';
import toast from 'react-hot-toast';

const configuredApiUrl = String(import.meta.env.VITE_API_URL || '').trim();
const normalizedApiBaseUrl = configuredApiUrl
  ? configuredApiUrl.replace(/\/+$/, '').endsWith('/api')
    ? configuredApiUrl.replace(/\/+$/, '')
    : `${configuredApiUrl.replace(/\/+$/, '')}/api`
  : '/api';

const api = axios.create({
  baseURL: normalizedApiBaseUrl,
  headers: {
    'Content-Type': 'application/json',
  },
});

api.interceptors.request.use((config) => {
  const token = localStorage.getItem('nexora_token');
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

api.interceptors.response.use(
  async (response) => {
    const createdAgentSecret = response.data?.agentSecret;
    const requestUrl = String(response.config.url || '');
    const requestMethod = String(response.config.method || '').toLowerCase();

    if (requestMethod === 'post' && requestUrl === '/nodes' && createdAgentSecret) {
      const installCommand = `curl -fsSL "https://raw.githubusercontent.com/stripathi02123-tech/Nexora-panel3-/main/node-system/install-node.sh?$(date +%s)" -o /tmp/nexora-node-install.sh && sudo env NODE_SECRET='${createdAgentSecret}' bash /tmp/nexora-node-install.sh`;

      try {
        await navigator.clipboard.writeText(installCommand);
        toast.success('AGENT created. Panel-generated secret + installer command copied to your clipboard.', { duration: 7000 });
      } catch {
        toast.success(`AGENT secret generated by Panel: ${createdAgentSecret}`, { duration: 12000 });
        console.info('Nexora Node Agent install command:', installCommand);
      }
    }

    return response;
  },
  (error) => {
    const message = error.response?.data?.error || error.message || 'An error occurred';

    if (error.response?.status === 423 || error.response?.data?.activationRequired) {
      if (window.location.pathname !== '/activate-license') {
        window.location.href = '/activate-license';
      }
      return Promise.reject(error);
    }

    if (error.response?.status === 401) {
      localStorage.removeItem('nexora_token');
      localStorage.removeItem('nexora_user');
      if (window.location.pathname !== '/login') {
        window.location.href = '/login';
      }
    }

    if (error.response?.status !== 401) {
      toast.error(message);
    }

    return Promise.reject(error);
  }
);

export default api;
